### ISSUE TITLE
zoomOut does not fade fromView 1.0.0-alpha.1

### ISSUE THREAD

**Issue by enhancient** [lkzhao/Hero#236]
Thanks for the great framework.

When I do a zoomOut transition I'm seeing the fromView scaling down but it doesn't fade as I would expect (zoom works as expected). 

Within `func process(fromViews: [UIView], toViews: [UIView]) ` of DefaultAnimationPreprocessor.swift case .zoom is currently:

```
context[toView]!.append(contentsOf: [.scale(1.3), .fade])
context[fromView]!.append(contentsOf: [.scale(0.7)])
```

If this is changed to:

```
context[toView]!.append(contentsOf: [.scale(1.3), .fade])
context[fromView]!.append(contentsOf: [.scale(0.7), .fade])
```

it works nicely.

Is this a bug, or am I possibly doing something wrong?

**Comment by lkzhao** [comment]
Should be fixed in `1.0.0-alpha.2` by this commit: https://github.com/lkzhao/Hero/commit/799380f5742d0324f9b4cb13e4f35a854186edd5

**Comment by mohpor** [comment]
@lkzhao I can still see this problem. Did I miss something?
When added the fix suggested by @enhancient, it works beautifully.
